steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build-ML-Py'
    dir: 'services/ml-py'
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/picca/picca-ml-py-stg:latest'
      - '.'
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/picca/picca-ml-py-stg:latest'
+options:
+  logging: CLOUD_LOGGING_ONLY
  - '-docker.pkg.dev//picca/picca-ml-py-stg:latest'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: asia-northeast1
