substitutions:
  _REGION: 'asia-northeast1'

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # === PRE-CHECKS ===
  - id: 'guard-region'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -lc
      - |-
        set -euo pipefail
        region="${_REGION}"
        if [[ -z "${region}" || "${region}" == "unset" ]]; then
          echo "ERROR: _REGION must be set in the Cloud Build trigger (e.g., asia-northeast1)." 1>&2
          exit 1
        fi
  - name: gcr.io/cloud-builders/docker
    args: ['build','-t','gcr.io/$PROJECT_ID/picca-api-go:$SHORT_SHA','.']
    dir: 'services/api-go'

  - name: gcr.io/cloud-builders/docker
    args: ['push','gcr.io/$PROJECT_ID/picca-api-go:$SHORT_SHA']

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        region="${_REGION}"
        service_default="picca-api-go-stg"
        if [ -n "${_SERVICE:-}" ]; then
          service="${_SERVICE}"
        else
          service="${service_default}"
        fi
        service_override="$(printenv SERVICE || true)"
        if [ -n "${service_override}" ]; then
          service="${service_override}"
        fi
        image_override="$(printenv IMAGE || true)"
        if [ -n "${image_override}" ]; then
          image="${image_override}"
        else
          image="gcr.io/$PROJECT_ID/picca-api-go:$SHORT_SHA"
        fi

        gcloud run deploy "${service}" --image "${image}" --region "${region}" --platform managed --allow-unauthenticated
