steps:
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','gcr.io/$PROJECT_ID/picca-api-go:$SHORT_SHA','.']
  dir: 'services/api-go'

- name: gcr.io/cloud-builders/docker
  args: ['push','gcr.io/$PROJECT_ID/picca-api-go:$SHORT_SHA']

- name: gcr.io/cloud-builders/gcloud
  args: [
    'run','deploy','picca-api-go-stg',
    '--image','gcr.io/$PROJECT_ID/picca-api-go:$SHORT_SHA',
    '--region','asia-northeast1',
    '--platform','managed',
    '--allow-unauthenticated'
  ]
