# services/ml_py/Dockerfile
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build-ML-Py'
    dir: 'services/ml_py'
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/picca-backend/picca-ml-py-stg:latest'
      - '.'
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/picca-backend/picca-ml-py-stg:latest'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: asia-northeast1
  _PROJECT: picca-dev-464810
  _MODEL_URI: "models/dcv/${TAG_NAME}/model.onnx"
# _MODEL_SHA256 is provided by the build trigger
