# cloudbuild-iac.yaml

substitutions:
  _REGION: 'unset'

steps:
  - id: 'tf-init'
    name: 'hashicorp/terraform:1.8'
    entrypoint: 'terraform'
    args: ['-chdir=infra', 'init', '-backend-config=backend.hcl']

  - id: 'tf-plan'
    name: 'hashicorp/terraform:1.8'
    entrypoint: 'terraform'
    args:
      - '-chdir=infra'
      - 'plan'
      - '-input=false'
      - '-out=tfplan'
      - "-var=project=${PROJECT_ID}"
      - "-var=region=${_REGION}"

  - id: 'tf-apply'
    name: 'hashicorp/terraform:1.8'
    entrypoint: 'terraform'
    args:
      - '-chdir=infra'
      - 'apply'
      - '-auto-approve'
      - 'tfplan'

options:
  logging: CLOUD_LOGGING_ONLY
