# infra/cloudbuild.yaml

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest"
      env: "DB_PASSWORD"

substitutions:
  _TF_ACTION: 'plan'
  _REGION: 'asia-northeast1'
  _SERVICE: 'picca-stg'

images:
  - "gcr.io/$PROJECT_ID/$_SERVICE:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: UNSPECIFIED

steps:
  # 1. unit tests
  - id: 'run-unit-tests'
    name: 'gcr.io/cloud-builders/npm'
    secretEnv:
      - 'DB_PASSWORD'
    args: ['ci']
  - id: 'run-tests'
    name: 'gcr.io/cloud-builders/npm'
    secretEnv:
      - 'DB_PASSWORD'
    args: ['test', '--', '--ci']


  # 2. Docker build & push
  
  - id: 'build-and-push-image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_SERVICE:$SHORT_SHA'
      - '.'
  - id: 'push-image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$_SERVICE:$SHORT_SHA'

  # 3. Cloud Run deployment
  - id: 'deploy-to-cloud-run'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--set-secrets=DB_PASSWORD=DB_PASSWORD:latest,API_KEY=API_KEY:latest'
      - '--allow-unauthenticated'
      - '--quiet'

  # 4. Terraform initialization
  - id: 'tf-init'
    name: 'hashicorp/terraform:1.8'
    entrypoint: 'terraform'
    args: ['init', '-input=false']
    dir: 'infra'

  # 5. Terraform Plan
  - id: 'tf-plan'
    name: 'hashicorp/terraform:1.8'
    entrypoint: 'terraform'
    args: ['plan', '-no-color', '-input=false', '-out=plan.tfout']
    dir: 'infra'

