availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest"
      env: "DB_PASSWORD"

substitutions:
  _TF_ACTION: 'plan'
  _SERVICE: 'picca-stg'

images:
  - "gcr.io/$PROJECT_ID/$_SERVICE:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: UNSPECIFIED

steps:
  # Guard: _REGION はトリガーで必須（未設定/ "unset" なら即失敗）
  - id: 'guard-region'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -lc
      - |
        set -euo pipefail
        region="${_REGION}"
        if [[ -z "${region}" || "${region}" == "unset" ]]; then
          echo "ERROR: _REGION must be set in the Cloud Build trigger (e.g., asia-northeast1)." 1>&2
          exit 1
        fi
  # 1. unit tests
  - id: 'install-and-test'
    name: 'node:20'
    entrypoint: 'bash'
    secretEnv:
      - 'DB_PASSWORD'
    args:
      - '-c'
      - |
        echo "Installing dependencies and running tests..."
        npm ci && npm test -- --ci

  # 2. Docker イメージをビルド＆プッシュ
  - id: 'build-and-push-image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE:$SHORT_SHA', '.']

  - id: 'push-image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE:$SHORT_SHA']

  # 3. Cloud Run へデプロイ
  - id: 'deploy-to-cloud-run'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -lc
      - |
        set -euo pipefail
        region="${_REGION}"
        service="${_SERVICE}"
        service_override="$(printenv SERVICE || true)"
        if [ -n "${service_override}" ]; then
          service="${service_override}"
        fi
        image_override="$(printenv IMAGE || true)"
        if [ -n "${image_override}" ]; then
          image="${image_override}"
        else
          image="gcr.io/$PROJECT_ID/${service}:$SHORT_SHA"
        fi

        gcloud run deploy "${service}" \
          --image "${image}" \
          --region "${region}" \
          --platform managed \
          --set-secrets=DB_PASSWORD=DB_PASSWORD:latest,API_KEY=API_KEY:latest \
          --allow-unauthenticated \
          --quiet

  # 4. Terraform 初期化
  - id: 'write-backend-config'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -lc
      - |
        set -euo pipefail
        bucket="${_TF_BACKEND_BUCKET:-}"
        prefix="${_TF_BACKEND_PREFIX:-terraform/state}"
        impersonate_sa="${_TF_BACKEND_IMPERSONATE_SA:-}"

        if [[ -z "${bucket}" ]]; then
          echo "ERROR: _TF_BACKEND_BUCKET must be set in the trigger substitutions." 1>&2
          exit 1
        fi

        {
          printf 'bucket = "%s"\n' "${bucket}"
          printf 'prefix = "%s"\n' "${prefix}"
          if [[ -n "${impersonate_sa}" ]]; then
            printf 'impersonate_service_account = "%s"\n' "${impersonate_sa}"
          fi
        } > infra/backend.hcl

  - id: 'tf-init'
    name: 'hashicorp/terraform:1.8'
    entrypoint: 'terraform'
    args: ['-chdir=infra', 'init', '-backend-config=backend.hcl']

  # 5. Terraform Plan
  - id: 'tf-plan'
    name: 'hashicorp/terraform:1.8'
    entrypoint: 'terraform'
    args:
      - '-chdir=infra'
      - 'plan'
      - '-no-color'
      - '-input=false'
      - '-out=plan.tfout'
      - '-var=project=${PROJECT_ID}'
      - '-var=region=${_REGION}'
