name: CI

on:
  push:
    branches: [ main, feat/**, fix/** ]
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements-dev.txt
            services/ml_py/requirements.txt

      - name: Install base dev deps (fast + lean)
        run: |
          python -m pip install -U pip wheel setuptools
          pip install ruff pytest "httpx<0.28" onnx

      - name: Ruff
        run: ruff check .

      - name: Install ml_py deps
        run: pip install -r services/ml_py/requirements.txt

      - name: Install torch (CPU)
        run: pip install torch

      - name: Pytest (JUnit)
        run: pytest -q -ra --junitxml=pytest.xml

      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: pytest.xml

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #  公式Action + Tokenをenvで明示
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITLEAKS_ENABLE_COMMENTS: "false"
        with:
          args: "--config=.gitleaks.toml --redact --verbose"
