name: CI

on:
  push:
    branches: [ main, feat/**, fix/** ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements-dev.txt
            services/ml_py/requirements.txt

      # dev ツールのみ先に入れて、まずはlintで早期Fail
      - name: Install dev deps (ruff/pytest etc.)
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt

      - name: Ruff
        run: ruff check .

      # ここまで通ったらML依存を入れる
      - name: Install ml_py deps
        run: |
          pip install -r services/ml_py/requirements.txt

      - name: Pytest
        run: pytest -q
