name: ML Export

on:
  workflow_dispatch:
    inputs:
      ckpt_path:
        description: 'Path to checkpoint'
        required: true
        default: 'checkpoints/model.pt'
      tag:
        description: 'Version tag'
        required: true
        default: 'v0.1.0'

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout
      - uses: actions/checkout@v4

      # 2) **Auth step – 必須**
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_JSON }}

      # 3) gcloud / gsutil setup
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 4) Python deps
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install torch onnx onnxruntime

      # 5) Export & upload
      - name: Prepare scripts
        run: chmod +x scripts/hash_model.sh

      - name: Export ONNX
        run: python scripts/export_onnx.py --ckpt ${{ inputs.ckpt_path }} --out model.onnx

      - name: Hash
        run: bash scripts/hash_model.sh model.onnx

      - name: Upload to GCS
        run: |
          gsutil cp model.onnx gs://picca-models/models/dcv/${{ inputs.tag }}/model.onnx
          gsutil cp model.onnx.sha256 gs://picca-models/models/dcv/${{ inputs.tag }}/model.sha256
